let url = new URL('http://127.0.0.1:5500/hello.html')
// let url = new URL('https://www.niet.co.in/')
console.log(url)
console.log(url.protocol)
console.log(url.host)
console.log(url.pathname)
console.log(url.search)
console.log(url.hash)